### ISSUE TITLE
Recent philosophers features

### ISSUE THREAD

**Issue by speed1992** [speed1992/quotes#151]

**Comment by kaleemullah786** [comment]
hey, i would like to work on it. can you provide more details

**Comment by speed1992** [comment]
In the philosopher selectbox, I require, the recently opened philosophers in the list at the top.

![IMG_20230821_175043](https://github.com/speed1992/quotes/assets/26317544/ad7f23b7-c80f-4dfa-a73e-c89001924866)

**Comment by kaleemullah786** [comment]
Hey, sorry i'm not available

**Comment by speed1992** [comment]
@kaleemullah786 ok cool, please come back whenever you feel convenient/comfortable

**Comment by speed1992** [comment]
this is completed
