### ISSUE TITLE
Quote : Add to favourites

### ISSUE THREAD

**Issue by speed1992** [speed1992/quotes#152]

**Comment by kaleemullah786** [comment]
hey, can you provide more details

**Comment by speed1992** [comment]
Hey Kaleem @kaleemullah786

Can you please understand this app and it's code.

It is mainly used in mobile view.

Try playing with this app and it's features.

Code part, did you look into the code?

What is your opinion on this feature? How can this be implemented?

**Comment by speed1992** [comment]
@kaleemullah786

https://speed1992.github.io/quotes/

This is prod.

**Comment by speed1992** [comment]
Notes for self:

Add date, philosopher, quote, quoteId in a favorite array and store it in redux.

Every 24 hours, sync with server

**Comment by speed1992** [comment]
Reuse homepage UI for favorites
