### ISSUE TITLE
Not showing bookmark feedback

### ISSUE THREAD

**Issue by Jaggazzz** [speed1992/quotes#30]

**Comment by speed1992** [comment]
@Jaggazzz 
Thanks for reporting the bug.

1. I have automated the quote location bookmarking process now. 

2. From now on, there will be no need to press the copy button to bookmark, it will be handled automatically by the web app. 

3. Therefore, no need to show bookmark feedback to the user. 

Please check, confirm, and acknowledge.

https://germans.herokuapp.com/

**Comment by Jaggazzz** [comment]
We still have to do copy if we want to save the bookmark.
I think the issue hasn't been resolved.

**Comment by Jaggazzz** [comment]
Thanx for resolving the issue.
Good work
